### ISSUE TITLE
fsSelection bold bit set on non-Bold styles

### ISSUE THREAD

**Issue by davelab6** [EkType/Mukta#26]
Sadly the latest release won't be possible to push to GF due to these errors:
```
ekmukta/EkMukta-ExtraBold.ttf:         fsSelection bold should be 0, is 1
muktavaani/MuktaVaani-SemiBold.ttf:    fsSelection bold should be 0, is 1
muktamahee/MuktaMahee-ExtraBold.ttf:   fsSelection bold should be 0, is 1
ekmukta/EkMukta-SemiBold.ttf:          fsSelection bold should be 0, is 1
muktamalar/MuktaMalar-ExtraBold.ttf:   fsSelection bold should be 0, is 1
mukta/Mukta-ExtraBold.ttf:             fsSelection bold should be 0, is 1
muktamalar/MuktaMalar-SemiBold.ttf:    fsSelection bold should be 0, is 1
muktavaani/MuktaVaani-ExtraBold.ttf:   fsSelection bold should be 0, is 1
mukta/Mukta-SemiBold.ttf:              fsSelection bold should be 0, is 1
muktamahee/MuktaMahee-SemiBold.ttf:    fsSelection bold should be 0, is 1
```

cc @m4rc1e @felipesanches

**Comment by felipesanches** [comment]
I've run fontbakery on the last 2 versions of this font on the google/fonts repo and it does report correctly that before today's update (1091d447b265fa24c141cca7be11b5dba31bf7e8) it was good:
```
INFO     INFO: Style is 'SemiBold'  
INFO     INFO: FSSEL_BOLD bit is 'False'  
INFO     OK: OS/2 fsSelection BOLD bit is properly set. 
```

And today (after the update) it is bad:
```
INFO     INFO: Style is 'SemiBold'  
INFO     INFO: FSSEL_BOLD bit is 'True'  
ERROR    OS/2 fsSelection BOLD bit should be reset. 
```

**Comment by m4rc1e** [comment]
@davelab6 @felipesanches 

This is my fault.
in FB's script nametablefromfilename.py, https://github.com/googlefonts/fontbakery/blob/master/bin/fontbakery-nametable-from-filename.py#L157-L171.

**Comment by felipesanches** [comment]
Yeah. You can change that bold conditional to: if style in ["Bold", "BoldItalic"] just like here:
https://github.com/googlefonts/fontbakery/blob/8ea30591740246b0625ef7b947c306e9ad2537a1/Lib/fontbakery/checks.py#L3507-L3511

**Comment by felipesanches** [comment]
Actually... I'll open an issue and fix it for you.

**Comment by m4rc1e** [comment]
@felipesanches thank you!

**Comment by girish-dalvi** [comment]
This seems like an issue in fontbakery-nametable-from-filename.py, the bit is set properly in the source TTX files.

**Comment by felipesanches** [comment]
@girish-dalvi I've just fixed it (on the closed FB pull request above) and Marc will probably update the fonts soon.

**Comment by girish-dalvi** [comment]
@felipesanches Thank you for the quick fix! 
@davelab6 @m4rc1e Since the bits are set properly in the source files, I'll close this issue.

**Comment by m4rc1e** [comment]
@girish-dalvi thanks and apologies for this.

**Comment by davelab6** [comment]
Yes good call Girish, thanks!!
